key_bindings:
  - { key: X, mods: Alt, chars: "\x1bX" } # M-x

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

schemes:
  pastel: &pastel # pastel theme sets dim=normal colors b/c idk what they should be
    # Default colors
    primary:
      background: '0x322957'
      foreground: '0xe5e5e5'

      dim_foreground: '0xe5e5e5'
      bright_foreground: '0xe5e5e5'
      dim_background: '0x322957'
      bright_background: '0x322957'

    # Normal colors
    normal:
      black: '0x000000'
      red: '0xff7092'
      green: '0x00faac'
      yellow: '0xfef96a'
      blue: '0x00beff'
      magenta: '0xde95ff'
      cyan: '0x85cbfd'
      white: '0xffffff'

    # Bright colors
    bright:
      black: '0x000000'
      red: '0xff89a3'
      green: '0x20f6bb'
      yellow: '0xfff687'
      blue: '0x1bcbfc'
      magenta: '0xe5adfd'
      cyan: '0x99d6fc'
      white: '0xfeffff'

    # Dim colors
    dim:
      black: '0x000000'
      red: '0xff7092'
      green: '0x00faac'
      yellow: '0xfef96a'
      blue: '0x00beff'
      magenta: '0xde95ff'
      cyan: '0x85cbfd'
      white: '0xffffff'

# pastel
colors: *pastel

visual_bell:
  animation: EaseOutExpo
  duration: 0

mouse:
  hide_when_typing: true
